name: coderco combined

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: install dependencies
        run: |
          cd chapter4
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: run tests
        run: |
          cd chapter4
          python -m unittest discover

      - name: notify use of success
        if: success()
        run: echo "test passed on python 3.10"

